### ISSUE TITLE
Make the terms and conditions and email disclaimer left aligned

### ISSUE THREAD

**Issue by jtmckibb** [sendchinatownlove/sendchinatownlove.github.io#142]
https://trello.com/c/8Il2r26X/423-feels-like-the-kerning-for-the-checkbox-text-and-the-following-text-is-different

**Comment by ppelayo** [comment]
Fix here - https://github.com/sendchinatownlove/sendchinatownlove.github.io/pull/163

don't think I have permission to link repos
