### ISSUE TITLE
Center donation button when it's alone

### ISSUE THREAD

**Issue by akill13** [sendchinatownlove/sendchinatownlove.github.io#162]
The donation button is to the left when it's alone
https://merchant.sendchinatownlove.com/wing-hing-seafood-restaurant
<img width="622" alt="Screen Shot 2020-05-29 at 3 05 36 AM" src="https://user-images.githubusercontent.com/34514252/83231901-4251b100-a15a-11ea-871a-0e32e2eeb0fb.png">

**Comment by TaskSquirrel** [comment]
Should the whole set of buttons be changed to match spec? (Donation on top spanning width)
